"""Seedance video generation core: chunk helpers, last-frame/cut extraction,
AVAI submit circuit breaker, moderation pre-flight, QC pipeline, ref resolution."""
# Split into ordered part-modules; importing them here preserves
# route-registration order and the public import surface.
from sw.seedance_avai import (
    AVAICircuitBreakerError,
    SEEDANCE_PRECHECK_ENABLED,
    _AVAI_AUDIT_LOG,
    _AVAI_KILLSWITCH_5MIN,
    _AVAI_KILL_SWITCH,
    _AVAI_MAX_PER_FP_10MIN,
    _AVAI_MAX_PER_MINUTE,
    _SEEDANCE_MODERATION_CHECKER_SYS,
    _avai_circuit_breaker_check,
    _avai_fingerprint,
    _avai_kill_switch_status,
    _avai_rate_lock,
    _avai_recent_submits,
    _avai_seedance_start,
    _avai_seedance_status,
    _avai_upload_local_image,
    _detect_cuts,
    _extract_keyframes_at_cuts,
    _extract_last_frame,
    _next_chunk_idx,
    _purge_continuity_sidecars,
    _seedance_chunks,
    _seedance_moderation_precheck,
)
from sw.seedance_qc import (
    QC_MAX_RETRIES,
    _QC_NON_ENGLISH_RE,
    _download_video,
    _ensure_char_avai_base_url,
    _ensure_loc_avai_url,
    _qc_can_pass,
    _qc_check_prompt_english,
    _qc_extract_audio,
    _qc_extract_frame_at,
    _qc_run_chunk,
    _qc_vision_grid_and_subs,
    _qc_whisper_detect,
    _resolve_ref_url,
)
